### ISSUE TITLE
Is it still working for Alfresco 5.0.d ?

### ISSUE THREAD

**Issue by jckermagoret** [loftuxab/manual-manager#8]
Hello,
it seems great. Is it still working in Alfresco 5 ?

Thanks,

JC

**Comment by loftux** [comment]
Yes, we actively use it in production for a couple of clients that use 5.0.d.
Should any updates be necessary for 5.1 I will do those as well, since this will be a requirement from our clients that use it. And we use it ourself of course.

**Comment by jckermagoret** [comment]
Hello,
I juste tested your addon on Alfresco CE 5.0.d. It's really great! I was looking for such a feature and you did it very well.

Congratulations,

JC
